// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.bosch.sdv.proto.models;

/**
 * Protobuf type {@code GpioRequest}
 */
public final class GpioRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GpioRequest)
    GpioRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GpioRequest.newBuilder() to construct.
  private GpioRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GpioRequest() {
    pinType_ = 0;
    defaultState_ = 0;
    state_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GpioRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GpioRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pinNo_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            pinType_ = rawValue;
            break;
          }
          case 24: {

            debounceValue_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            defaultState_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          case 48: {

            inverted_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.bosch.sdv.proto.models.Gpio.internal_static_GpioRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.bosch.sdv.proto.models.Gpio.internal_static_GpioRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.bosch.sdv.proto.models.GpioRequest.class, in.bosch.sdv.proto.models.GpioRequest.Builder.class);
  }

  public static final int PINNO_FIELD_NUMBER = 1;
  private int pinNo_;
  /**
   * <code>int32 pinNo = 1;</code>
   * @return The pinNo.
   */
  @java.lang.Override
  public int getPinNo() {
    return pinNo_;
  }

  public static final int PINTYPE_FIELD_NUMBER = 2;
  private int pinType_;
  /**
   * <code>.GpioType pinType = 2;</code>
   * @return The enum numeric value on the wire for pinType.
   */
  @java.lang.Override public int getPinTypeValue() {
    return pinType_;
  }
  /**
   * <code>.GpioType pinType = 2;</code>
   * @return The pinType.
   */
  @java.lang.Override public in.bosch.sdv.proto.models.GpioType getPinType() {
    @SuppressWarnings("deprecation")
    in.bosch.sdv.proto.models.GpioType result = in.bosch.sdv.proto.models.GpioType.valueOf(pinType_);
    return result == null ? in.bosch.sdv.proto.models.GpioType.UNRECOGNIZED : result;
  }

  public static final int DEBOUNCE_VALUE_FIELD_NUMBER = 3;
  private int debounceValue_;
  /**
   * <code>int32 debounce_value = 3;</code>
   * @return The debounceValue.
   */
  @java.lang.Override
  public int getDebounceValue() {
    return debounceValue_;
  }

  public static final int DEFAULTSTATE_FIELD_NUMBER = 4;
  private int defaultState_;
  /**
   * <code>.GpioDigitalState defaultState = 4;</code>
   * @return The enum numeric value on the wire for defaultState.
   */
  @java.lang.Override public int getDefaultStateValue() {
    return defaultState_;
  }
  /**
   * <code>.GpioDigitalState defaultState = 4;</code>
   * @return The defaultState.
   */
  @java.lang.Override public in.bosch.sdv.proto.models.GpioDigitalState getDefaultState() {
    @SuppressWarnings("deprecation")
    in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(defaultState_);
    return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 5;
  private int state_;
  /**
   * <code>.GpioDigitalState state = 5;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.GpioDigitalState state = 5;</code>
   * @return The state.
   */
  @java.lang.Override public in.bosch.sdv.proto.models.GpioDigitalState getState() {
    @SuppressWarnings("deprecation")
    in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(state_);
    return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
  }

  public static final int INVERTED_FIELD_NUMBER = 6;
  private boolean inverted_;
  /**
   * <code>bool inverted = 6;</code>
   * @return The inverted.
   */
  @java.lang.Override
  public boolean getInverted() {
    return inverted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pinNo_ != 0) {
      output.writeInt32(1, pinNo_);
    }
    if (pinType_ != in.bosch.sdv.proto.models.GpioType.INPUT.getNumber()) {
      output.writeEnum(2, pinType_);
    }
    if (debounceValue_ != 0) {
      output.writeInt32(3, debounceValue_);
    }
    if (defaultState_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      output.writeEnum(4, defaultState_);
    }
    if (state_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      output.writeEnum(5, state_);
    }
    if (inverted_ != false) {
      output.writeBool(6, inverted_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pinNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pinNo_);
    }
    if (pinType_ != in.bosch.sdv.proto.models.GpioType.INPUT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, pinType_);
    }
    if (debounceValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, debounceValue_);
    }
    if (defaultState_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, defaultState_);
    }
    if (state_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, state_);
    }
    if (inverted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, inverted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof in.bosch.sdv.proto.models.GpioRequest)) {
      return super.equals(obj);
    }
    in.bosch.sdv.proto.models.GpioRequest other = (in.bosch.sdv.proto.models.GpioRequest) obj;

    if (getPinNo()
        != other.getPinNo()) return false;
    if (pinType_ != other.pinType_) return false;
    if (getDebounceValue()
        != other.getDebounceValue()) return false;
    if (defaultState_ != other.defaultState_) return false;
    if (state_ != other.state_) return false;
    if (getInverted()
        != other.getInverted()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PINNO_FIELD_NUMBER;
    hash = (53 * hash) + getPinNo();
    hash = (37 * hash) + PINTYPE_FIELD_NUMBER;
    hash = (53 * hash) + pinType_;
    hash = (37 * hash) + DEBOUNCE_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getDebounceValue();
    hash = (37 * hash) + DEFAULTSTATE_FIELD_NUMBER;
    hash = (53 * hash) + defaultState_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + INVERTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInverted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.bosch.sdv.proto.models.GpioRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GpioRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GpioRequest)
      in.bosch.sdv.proto.models.GpioRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.bosch.sdv.proto.models.GpioRequest.class, in.bosch.sdv.proto.models.GpioRequest.Builder.class);
    }

    // Construct using in.srini91.learn.proto.models.GpioRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pinNo_ = 0;

      pinType_ = 0;

      debounceValue_ = 0;

      defaultState_ = 0;

      state_ = 0;

      inverted_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioRequest_descriptor;
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioRequest getDefaultInstanceForType() {
      return in.bosch.sdv.proto.models.GpioRequest.getDefaultInstance();
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioRequest build() {
      in.bosch.sdv.proto.models.GpioRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioRequest buildPartial() {
      in.bosch.sdv.proto.models.GpioRequest result = new in.bosch.sdv.proto.models.GpioRequest(this);
      result.pinNo_ = pinNo_;
      result.pinType_ = pinType_;
      result.debounceValue_ = debounceValue_;
      result.defaultState_ = defaultState_;
      result.state_ = state_;
      result.inverted_ = inverted_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.bosch.sdv.proto.models.GpioRequest) {
        return mergeFrom((in.bosch.sdv.proto.models.GpioRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.bosch.sdv.proto.models.GpioRequest other) {
      if (other == in.bosch.sdv.proto.models.GpioRequest.getDefaultInstance()) return this;
      if (other.getPinNo() != 0) {
        setPinNo(other.getPinNo());
      }
      if (other.pinType_ != 0) {
        setPinTypeValue(other.getPinTypeValue());
      }
      if (other.getDebounceValue() != 0) {
        setDebounceValue(other.getDebounceValue());
      }
      if (other.defaultState_ != 0) {
        setDefaultStateValue(other.getDefaultStateValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.getInverted() != false) {
        setInverted(other.getInverted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.bosch.sdv.proto.models.GpioRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.bosch.sdv.proto.models.GpioRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pinNo_ ;
    /**
     * <code>int32 pinNo = 1;</code>
     * @return The pinNo.
     */
    @java.lang.Override
    public int getPinNo() {
      return pinNo_;
    }
    /**
     * <code>int32 pinNo = 1;</code>
     * @param value The pinNo to set.
     * @return This builder for chaining.
     */
    public Builder setPinNo(int value) {
      
      pinNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pinNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPinNo() {
      
      pinNo_ = 0;
      onChanged();
      return this;
    }

    private int pinType_ = 0;
    /**
     * <code>.GpioType pinType = 2;</code>
     * @return The enum numeric value on the wire for pinType.
     */
    @java.lang.Override public int getPinTypeValue() {
      return pinType_;
    }
    /**
     * <code>.GpioType pinType = 2;</code>
     * @param value The enum numeric value on the wire for pinType to set.
     * @return This builder for chaining.
     */
    public Builder setPinTypeValue(int value) {
      
      pinType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GpioType pinType = 2;</code>
     * @return The pinType.
     */
    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioType getPinType() {
      @SuppressWarnings("deprecation")
      in.bosch.sdv.proto.models.GpioType result = in.bosch.sdv.proto.models.GpioType.valueOf(pinType_);
      return result == null ? in.bosch.sdv.proto.models.GpioType.UNRECOGNIZED : result;
    }
    /**
     * <code>.GpioType pinType = 2;</code>
     * @param value The pinType to set.
     * @return This builder for chaining.
     */
    public Builder setPinType(in.bosch.sdv.proto.models.GpioType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pinType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GpioType pinType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPinType() {
      
      pinType_ = 0;
      onChanged();
      return this;
    }

    private int debounceValue_ ;
    /**
     * <code>int32 debounce_value = 3;</code>
     * @return The debounceValue.
     */
    @java.lang.Override
    public int getDebounceValue() {
      return debounceValue_;
    }
    /**
     * <code>int32 debounce_value = 3;</code>
     * @param value The debounceValue to set.
     * @return This builder for chaining.
     */
    public Builder setDebounceValue(int value) {
      
      debounceValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 debounce_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDebounceValue() {
      
      debounceValue_ = 0;
      onChanged();
      return this;
    }

    private int defaultState_ = 0;
    /**
     * <code>.GpioDigitalState defaultState = 4;</code>
     * @return The enum numeric value on the wire for defaultState.
     */
    @java.lang.Override public int getDefaultStateValue() {
      return defaultState_;
    }
    /**
     * <code>.GpioDigitalState defaultState = 4;</code>
     * @param value The enum numeric value on the wire for defaultState to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultStateValue(int value) {
      
      defaultState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState defaultState = 4;</code>
     * @return The defaultState.
     */
    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioDigitalState getDefaultState() {
      @SuppressWarnings("deprecation")
      in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(defaultState_);
      return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
    }
    /**
     * <code>.GpioDigitalState defaultState = 4;</code>
     * @param value The defaultState to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultState(in.bosch.sdv.proto.models.GpioDigitalState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      defaultState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState defaultState = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultState() {
      
      defaultState_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.GpioDigitalState state = 5;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.GpioDigitalState state = 5;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState state = 5;</code>
     * @return The state.
     */
    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioDigitalState getState() {
      @SuppressWarnings("deprecation")
      in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(state_);
      return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
    }
    /**
     * <code>.GpioDigitalState state = 5;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(in.bosch.sdv.proto.models.GpioDigitalState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState state = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }

    private boolean inverted_ ;
    /**
     * <code>bool inverted = 6;</code>
     * @return The inverted.
     */
    @java.lang.Override
    public boolean getInverted() {
      return inverted_;
    }
    /**
     * <code>bool inverted = 6;</code>
     * @param value The inverted to set.
     * @return This builder for chaining.
     */
    public Builder setInverted(boolean value) {
      
      inverted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool inverted = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInverted() {
      
      inverted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GpioRequest)
  }

  // @@protoc_insertion_point(class_scope:GpioRequest)
  private static final in.bosch.sdv.proto.models.GpioRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.bosch.sdv.proto.models.GpioRequest();
  }

  public static in.bosch.sdv.proto.models.GpioRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GpioRequest>
      PARSER = new com.google.protobuf.AbstractParser<GpioRequest>() {
    @java.lang.Override
    public GpioRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GpioRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GpioRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GpioRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public in.bosch.sdv.proto.models.GpioRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

