// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.bosch.sdv.proto.models;

/**
 * Protobuf type {@code GpioData}
 */
public final class GpioData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GpioData)
    GpioDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GpioData.newBuilder() to construct.
  private GpioData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GpioData() {
    digitalState_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GpioData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GpioData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            digitalState_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.bosch.sdv.proto.models.Gpio.internal_static_GpioData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.bosch.sdv.proto.models.Gpio.internal_static_GpioData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.bosch.sdv.proto.models.GpioData.class, in.bosch.sdv.proto.models.GpioData.Builder.class);
  }

  public static final int DIGITALSTATE_FIELD_NUMBER = 1;
  private int digitalState_;
  /**
   * <code>.GpioDigitalState digitalState = 1;</code>
   * @return The enum numeric value on the wire for digitalState.
   */
  @java.lang.Override public int getDigitalStateValue() {
    return digitalState_;
  }
  /**
   * <code>.GpioDigitalState digitalState = 1;</code>
   * @return The digitalState.
   */
  @java.lang.Override public in.bosch.sdv.proto.models.GpioDigitalState getDigitalState() {
    @SuppressWarnings("deprecation")
    in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(digitalState_);
    return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (digitalState_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      output.writeEnum(1, digitalState_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (digitalState_ != in.bosch.sdv.proto.models.GpioDigitalState.LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, digitalState_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof in.bosch.sdv.proto.models.GpioData)) {
      return super.equals(obj);
    }
    in.bosch.sdv.proto.models.GpioData other = (in.bosch.sdv.proto.models.GpioData) obj;

    if (digitalState_ != other.digitalState_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIGITALSTATE_FIELD_NUMBER;
    hash = (53 * hash) + digitalState_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.bosch.sdv.proto.models.GpioData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.bosch.sdv.proto.models.GpioData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GpioData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GpioData)
      in.bosch.sdv.proto.models.GpioDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.bosch.sdv.proto.models.GpioData.class, in.bosch.sdv.proto.models.GpioData.Builder.class);
    }

    // Construct using in.srini91.learn.proto.models.GpioData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      digitalState_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.bosch.sdv.proto.models.Gpio.internal_static_GpioData_descriptor;
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioData getDefaultInstanceForType() {
      return in.bosch.sdv.proto.models.GpioData.getDefaultInstance();
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioData build() {
      in.bosch.sdv.proto.models.GpioData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioData buildPartial() {
      in.bosch.sdv.proto.models.GpioData result = new in.bosch.sdv.proto.models.GpioData(this);
      result.digitalState_ = digitalState_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.bosch.sdv.proto.models.GpioData) {
        return mergeFrom((in.bosch.sdv.proto.models.GpioData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.bosch.sdv.proto.models.GpioData other) {
      if (other == in.bosch.sdv.proto.models.GpioData.getDefaultInstance()) return this;
      if (other.digitalState_ != 0) {
        setDigitalStateValue(other.getDigitalStateValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.bosch.sdv.proto.models.GpioData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.bosch.sdv.proto.models.GpioData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int digitalState_ = 0;
    /**
     * <code>.GpioDigitalState digitalState = 1;</code>
     * @return The enum numeric value on the wire for digitalState.
     */
    @java.lang.Override public int getDigitalStateValue() {
      return digitalState_;
    }
    /**
     * <code>.GpioDigitalState digitalState = 1;</code>
     * @param value The enum numeric value on the wire for digitalState to set.
     * @return This builder for chaining.
     */
    public Builder setDigitalStateValue(int value) {
      
      digitalState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState digitalState = 1;</code>
     * @return The digitalState.
     */
    @java.lang.Override
    public in.bosch.sdv.proto.models.GpioDigitalState getDigitalState() {
      @SuppressWarnings("deprecation")
      in.bosch.sdv.proto.models.GpioDigitalState result = in.bosch.sdv.proto.models.GpioDigitalState.valueOf(digitalState_);
      return result == null ? in.bosch.sdv.proto.models.GpioDigitalState.UNRECOGNIZED : result;
    }
    /**
     * <code>.GpioDigitalState digitalState = 1;</code>
     * @param value The digitalState to set.
     * @return This builder for chaining.
     */
    public Builder setDigitalState(in.bosch.sdv.proto.models.GpioDigitalState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      digitalState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GpioDigitalState digitalState = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDigitalState() {
      
      digitalState_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GpioData)
  }

  // @@protoc_insertion_point(class_scope:GpioData)
  private static final in.bosch.sdv.proto.models.GpioData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.bosch.sdv.proto.models.GpioData();
  }

  public static in.bosch.sdv.proto.models.GpioData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GpioData>
      PARSER = new com.google.protobuf.AbstractParser<GpioData>() {
    @java.lang.Override
    public GpioData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GpioData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GpioData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GpioData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public in.bosch.sdv.proto.models.GpioData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

