// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.bosch.sdv.proto.models;

public interface GpioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GpioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pinNo = 1;</code>
   * @return The pinNo.
   */
  int getPinNo();

  /**
   * <code>.GpioType pinType = 2;</code>
   * @return The enum numeric value on the wire for pinType.
   */
  int getPinTypeValue();
  /**
   * <code>.GpioType pinType = 2;</code>
   * @return The pinType.
   */
  in.bosch.sdv.proto.models.GpioType getPinType();

  /**
   * <code>int32 debounce_value = 3;</code>
   * @return The debounceValue.
   */
  int getDebounceValue();

  /**
   * <code>.GpioDigitalState defaultState = 4;</code>
   * @return The enum numeric value on the wire for defaultState.
   */
  int getDefaultStateValue();
  /**
   * <code>.GpioDigitalState defaultState = 4;</code>
   * @return The defaultState.
   */
  in.bosch.sdv.proto.models.GpioDigitalState getDefaultState();

  /**
   * <code>.GpioDigitalState state = 5;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.GpioDigitalState state = 5;</code>
   * @return The state.
   */
  in.bosch.sdv.proto.models.GpioDigitalState getState();

  /**
   * <code>bool inverted = 6;</code>
   * @return The inverted.
   */
  boolean getInverted();
}
