// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.bosch.sdv.proto.models;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
