// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.srini91.learn.proto.models;

public interface GpioDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GpioData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GpioDigitalState digitalState = 1;</code>
   * @return The enum numeric value on the wire for digitalState.
   */
  int getDigitalStateValue();
  /**
   * <code>.GpioDigitalState digitalState = 1;</code>
   * @return The digitalState.
   */
  in.srini91.learn.proto.models.GpioDigitalState getDigitalState();
}
