// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.srini91.learn.proto.models;

public final class Gpio {
  private Gpio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GpioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GpioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GpioData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GpioData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LedStripData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LedStripData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngpio.proto\"\255\001\n\013GpioRequest\022\r\n\005pinNo\030\001 " +
      "\001(\005\022\032\n\007pinType\030\002 \001(\0162\t.GpioType\022\026\n\016debou" +
      "nce_value\030\003 \001(\005\022\'\n\014defaultState\030\004 \001(\0162\021." +
      "GpioDigitalState\022 \n\005state\030\005 \001(\0162\021.GpioDi" +
      "gitalState\022\020\n\010inverted\030\006 \001(\010\"3\n\010GpioData" +
      "\022\'\n\014digitalState\030\001 \001(\0162\021.GpioDigitalStat" +
      "e\"m\n\014LedStripData\022\022\n\npixelCount\030\001 \001(\005\022\022\n" +
      "\nbrightness\030\002 \001(\001\022\020\n\010allPixel\030\003 \001(\010\022\017\n\007p" +
      "ixelNo\030\004 \001(\005\022\022\n\npixelColor\030\005 \001(\005*!\n\010Gpio" +
      "Type\022\t\n\005INPUT\020\000\022\n\n\006OUTPUT\020\001*%\n\020GpioDigit" +
      "alState\022\007\n\003LOW\020\000\022\010\n\004HIGH\020\0012\233\001\n\021PodmanDem" +
      "oService\022*\n\rreadGpioState\022\014.GpioRequest\032" +
      "\t.GpioData0\001\022*\n\rwriteGpioData\022\014.GpioRequ" +
      "est\032\t.GpioData(\001\022.\n\014ledStripData\022\r.LedSt" +
      "ripData\032\r.LedStripData(\001B!\n\035in.srini91.l" +
      "earn.proto.modelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GpioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GpioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GpioRequest_descriptor,
        new java.lang.String[] { "PinNo", "PinType", "DebounceValue", "DefaultState", "State", "Inverted", });
    internal_static_GpioData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GpioData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GpioData_descriptor,
        new java.lang.String[] { "DigitalState", });
    internal_static_LedStripData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LedStripData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LedStripData_descriptor,
        new java.lang.String[] { "PixelCount", "Brightness", "AllPixel", "PixelNo", "PixelColor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
