// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpio.proto

package in.srini91.learn.proto.models;

public interface LedStripDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LedStripData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pixelCount = 1;</code>
   * @return The pixelCount.
   */
  int getPixelCount();

  /**
   * <code>double brightness = 2;</code>
   * @return The brightness.
   */
  double getBrightness();

  /**
   * <code>bool allPixel = 3;</code>
   * @return The allPixel.
   */
  boolean getAllPixel();

  /**
   * <code>int32 pixelNo = 4;</code>
   * @return The pixelNo.
   */
  int getPixelNo();

  /**
   * <code>int32 pixelColor = 5;</code>
   * @return The pixelColor.
   */
  int getPixelColor();
}
